spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: Lucia
    password: Hiberus1125
    driverClassName: oracle.jdbc.OracleDriver
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: testossot@gmail.com
    password: vztyucugdlyiudaf